check that changelog also contains link to diff

diff --git a/.git_hooks/pre-push b/.git_hooks/pre-push
--- a/.git_hooks/pre-push
+++ b/.git_hooks/pre-push
@@ -44,8 +44,12 @@ fi
 VERSION=$(egrep 'version = ".*"' pyproject.toml | cut -d \" -f 2)
 if test -z "$VERSION"; then echo 'version not found in pyproject.toml'; STATUS=1; fi
 if ! grep -q "$VERSION" CHANGELOG.md
-then echo 'version not found in changelog'; STATUS=1
+then echo "$VERSION not found in changelog"; STATUS=1
 else echo "$VERSION found in CHANGELOG.md, thanks"
+fi
+if ! fgrep -q "...$VERSION" CHANGELOG.md
+then echo "link to $VERSION diff not found in changelog"; STATUS=1
+else echo "link to $VERSION diff found in CHANGELOG.md, thanks"
 fi
 
 if [ $STATUS -gt 0 ]; then
